/**
 * languages.js
 * Top 50 most widely spoken world languages + Tamil (51st).
 * The `code` field is the full language name sent to the AI prompt.
 */
export const LANGUAGES = [
  { code: 'Mandarin Chinese', name: 'Mandarin Chinese', native: '中文 (普通话)' },
  { code: 'Spanish',          name: 'Spanish',          native: 'Español' },
  { code: 'Hindi',            name: 'Hindi',            native: 'हिन्दी' },
  { code: 'Arabic',           name: 'Arabic',           native: 'العربية' },
  { code: 'Bengali',          name: 'Bengali',          native: 'বাংলা' },
  { code: 'French',           name: 'French',           native: 'Français' },
  { code: 'Portuguese',       name: 'Portuguese',       native: 'Português' },
  { code: 'Russian',          name: 'Russian',          native: 'Русский' },
  { code: 'Japanese',         name: 'Japanese',         native: '日本語' },
  { code: 'Punjabi',          name: 'Punjabi',          native: 'ਪੰਜਾਬੀ' },
  { code: 'Marathi',          name: 'Marathi',          native: 'मराठी' },
  { code: 'Telugu',           name: 'Telugu',           native: 'తెలుగు' },
  { code: 'Turkish',          name: 'Turkish',          native: 'Türkçe' },
  { code: 'Korean',           name: 'Korean',           native: '한국어' },
  { code: 'Vietnamese',       name: 'Vietnamese',       native: 'Tiếng Việt' },
  { code: 'German',           name: 'German',           native: 'Deutsch' },
  { code: 'Urdu',             name: 'Urdu',             native: 'اردو' },
  { code: 'Italian',          name: 'Italian',          native: 'Italiano' },
  { code: 'Gujarati',         name: 'Gujarati',         native: 'ગુજરાતી' },
  { code: 'Persian',          name: 'Persian (Farsi)',  native: 'فارسی' },
  { code: 'Indonesian',       name: 'Indonesian',       native: 'Bahasa Indonesia' },
  { code: 'Hausa',            name: 'Hausa',            native: 'Hausa' },
  { code: 'Pashto',           name: 'Pashto',           native: 'پښتو' },
  { code: 'Yoruba',           name: 'Yoruba',           native: 'Yorùbá' },
  { code: 'Malay',            name: 'Malay',            native: 'Bahasa Melayu' },
  { code: 'Burmese',          name: 'Burmese',          native: 'မြန်မာ' },
  { code: 'Amharic',          name: 'Amharic',          native: 'አማርኛ' },
  { code: 'Odia',             name: 'Odia',             native: 'ଓଡ଼ିଆ' },
  { code: 'Filipino',         name: 'Filipino (Tagalog)', native: 'Filipino' },
  { code: 'Sindhi',           name: 'Sindhi',           native: 'سنڌي' },
  { code: 'Polish',           name: 'Polish',           native: 'Polski' },
  { code: 'Zulu',             name: 'Zulu',             native: 'isiZulu' },
  { code: 'Xhosa',            name: 'Xhosa',            native: 'isiXhosa' },
  { code: 'Kannada',          name: 'Kannada',          native: 'ಕನ್ನಡ' },
  { code: 'Romanian',         name: 'Romanian',         native: 'Română' },
  { code: 'Ukrainian',        name: 'Ukrainian',        native: 'Українська' },
  { code: 'Igbo',             name: 'Igbo',             native: 'Igbo' },
  { code: 'Dutch',            name: 'Dutch',            native: 'Nederlands' },
  { code: 'Swahili',          name: 'Swahili',          native: 'Kiswahili' },
  { code: 'Thai',             name: 'Thai',             native: 'ภาษาไทย' },
  { code: 'Malayalam',        name: 'Malayalam',        native: 'മലയാളം' },
  { code: 'Cantonese',        name: 'Cantonese',        native: '粵語' },
  { code: 'Hungarian',        name: 'Hungarian',        native: 'Magyar' },
  { code: 'Czech',            name: 'Czech',            native: 'Čeština' },
  { code: 'Greek',            name: 'Greek',            native: 'Ελληνικά' },
  { code: 'Swedish',          name: 'Swedish',          native: 'Svenska' },
  { code: 'Hebrew',           name: 'Hebrew',           native: 'עברית' },
  { code: 'Finnish',          name: 'Finnish',          native: 'Suomi' },
  { code: 'Norwegian',        name: 'Norwegian',        native: 'Norsk' },
  { code: 'Serbian',          name: 'Serbian',          native: 'Српски' },
  { code: 'Tamil',            name: 'Tamil',            native: 'தமிழ்' },  // 51st
];
